
import type { FormationSlot } from './types';

export type FormationPreset = {
  name: string;
  slots: FormationSlot[];
};

// Field coordinate system:
// top: 0% is attacking goal, 100% is defending goal
// left: 0% is the left side of the field, 100% is the right side
const positionGrid: { [key: string]: { top: number; left: number } } = {
  'GK': { top: 90, left: 50 },
  
  'RB': { top: 75, left: 85 },
  'LB': { top: 75, left: 15 },
  'CB-L': { top: 78, left: 35 },
  'CB-C': { top: 80, left: 50 },
  'CB-R': { top: 78, left: 65 },
  
  'RM': { top: 50, left: 80 },
  'LM': { top: 50, left: 20 },
  'CDM': { top: 60, left: 50 },
  'CM-L': { top: 50, left: 35 },
  'CM-C': { top: 50, left: 50 },
  'CM-R': { top: 50, left: 65 },
  'CAM': { top: 35, left: 50 },

  'RW': { top: 25, left: 85 },
  'LW': { top: 25, left: 15 },
  'CF-L': { top: 28, left: 40 },
  'CF-R': { top: 28, left: 60 },
  'ST': { top: 15, left: 50 },
  'ST-L': { top: 15, left: 40 },
  'ST-R': { top: 15, left: 60 },
};

const getPos = (key: string) => positionGrid[key] || { top: 50, left: 50 };

export const formationPresets: FormationPreset[] = [
   {
    name: '3-1-4-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '3-4-1-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '3-4-2-1',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'CF', styles: [], ...getPos('CF-L') },
      { position: 'CF', styles: [], ...getPos('CF-R') },
      { position: 'ST', styles: [], ...getPos('ST') },
    ],
  },
  {
    name: '3-4-3',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'ST', styles: [], ...getPos('ST') },
      { position: 'RW', styles: [], ...getPos('RW') },
    ],
  },
  {
    name: '3-5-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-1-2-1-2 (Rombo)',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-1-2-1-2 (Rombo Abierto)',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-1-3-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-1-4-1',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'ST', styles: [], ...getPos('ST') },
    ],
  },
  {
    name: '4-2-1-3',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CM-L') },
      { position: 'CDM', styles: [], ...getPos('CM-R') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'ST', styles: [], ...getPos('ST') },
      { position: 'RW', styles: [], ...getPos('RW') },
    ],
  },
  {
    name: '4-2-2-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CM-L') },
      { position: 'CDM', styles: [], ...getPos('CM-R') },
      { position: 'CAM', styles: [], ...getPos('CF-L') },
      { position: 'CAM', styles: [], ...getPos('CF-R') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
    {
    name: '4-2-3-1',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], top: 60, left: 35 },
      { position: 'CDM', styles: [], top: 60, left: 65 },
      { position: 'LM', styles: [], top: 45, left: 15 },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'RM', styles: [], top: 45, left: 85 },
      { position: 'ST', styles: [], ...getPos('ST') },
    ],
  },
  {
    name: '4-2-4',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'RW', styles: [], ...getPos('RW') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-3-1-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-C') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-3-2-1 (Árbol de Navidad)',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-C') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'CF', styles: [], ...getPos('CF-L') },
      { position: 'CF', styles: [], ...getPos('CF-R') },
      { position: 'ST', styles: [], ...getPos('ST') },
    ],
  },
  {
    name: '4-3-3 (Holding)',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'ST', styles: [], ...getPos('ST') },
      { position: 'RW', styles: [], ...getPos('RW') },
    ],
  },
  {
    name: '4-3-3 (Attack)',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'ST', styles: [], ...getPos('ST') },
      { position: 'RW', styles: [], ...getPos('RW') },
    ],
  },
  {
    name: '4-3-3 (False 9)',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'CF', styles: [], ...getPos('ST') }, // False 9 as CF
      { position: 'RW', styles: [], ...getPos('RW') },
    ],
  },
  {
    name: '4-4-1-1',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'CF', styles: [], ...getPos('CAM') },
      { position: 'ST', styles: [], ...getPos('ST') },
    ],
  },
  {
    name: '4-4-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '4-5-1',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LB', styles: [], ...getPos('LB') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RB', styles: [], ...getPos('RB') },
      { position: 'LM', styles: [], ...getPos('LM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-C') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'RM', styles: [], ...getPos('RM') },
      { position: 'ST', styles: [], ...getPos('ST') },
    ],
  },
  {
    name: '5-2-1-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LWB', styles: [], ...getPos('LM') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RWB', styles: [], ...getPos('RM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'CAM', styles: [], ...getPos('CAM') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: '5-2-3',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LWB', styles: [], ...getPos('LM') },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RWB', styles: [], ...getPos('RM') },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'LW', styles: [], ...getPos('LW') },
      { position: 'ST', styles: [], ...getPos('ST') },
      { position: 'RW', styles: [], ...getPos('RW') },
    ],
  },
  {
    name: '5-3-2',
    slots: [
      { position: 'GK', styles: [], ...getPos('GK') },
      { position: 'LWB', styles: [], top: 70, left: 10 },
      { position: 'CB', styles: [], ...getPos('CB-L') },
      { position: 'CB', styles: [], ...getPos('CB-C') },
      { position: 'CB', styles: [], ...getPos('CB-R') },
      { position: 'RWB', styles: [], top: 70, left: 90 },
      { position: 'CM', styles: [], ...getPos('CM-L') },
      { position: 'CDM', styles: [], ...getPos('CDM') },
      { position: 'CM', styles: [], ...getPos('CM-R') },
      { position: 'ST', styles: [], ...getPos('ST-L') },
      { position: 'ST', styles: [], ...getPos('ST-R') },
    ],
  },
  {
    name: 'Custom',
    slots: Array(11).fill(null).map((_, i) => ({
        position: 'ST',
        styles: [],
        top: 20 + Math.floor(i / 3) * 25,
        left: 25 + (i % 3) * 25,
    })),
  },
];
