
import type { FormationSlot } from './types';

export type FormationPreset = {
  name: string;
  slots: FormationSlot[];
};

// Field coordinate system:
// top: 0% is attacking goal, 100% is defending goal
// left: 0% is the left side of the field, 100% is the right side
const positionGrid: { [key: string]: { top: number; left: number } } = {
  'PT': { top: 90, left: 50 },
  
  'LD': { top: 75, left: 85 },
  'DFC-L': { top: 78, left: 35 },
  'DFC-C': { top: 80, left: 50 },
  'DFC-R': { top: 78, left: 65 },
  'LI': { top: 75, left: 15 },
  
  'MDD': { top: 50, left: 80 },
  'MCD': { top: 60, left: 50 },
  'MC-L': { top: 50, left: 35 },
  'MC-C': { top: 50, left: 50 },
  'MC-R': { top: 50, left: 65 },
  'MDI': { top: 50, left: 20 },
  
  'EXD': { top: 25, left: 85 },
  'MO-L': { top: 35, left: 35 },
  'MO-C': { top: 35, left: 50 },
  'MO-R': { top: 35, left: 65 },
  'SD-L': { top: 28, left: 40 },
  'SD-R': { top: 28, left: 60 },
  'EXI': { top: 25, left: 15 },
  
  'DC': { top: 15, left: 50 },
  'DC-L': { top: 15, left: 40 },
  'DC-R': { top: 15, left: 60 },
};

const getPos = (key: string) => positionGrid[key] || { top: 50, left: 50 };

export const formationPresets: FormationPreset[] = [
   {
    name: '3-1-4-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '3-4-1-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '3-4-2-1',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'MO', styles: [], ...getPos('MO-L') },
      { position: 'MO', styles: [], ...getPos('MO-R') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
  {
    name: '3-4-3',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'DC', styles: [], ...getPos('DC') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '3-5-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-1-2-1-2 (Rombo)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-1-2-1-2 (Rombo Abierto)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-1-3-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-1-4-1',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
  {
    name: '4-2-1-3',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MC-L') },
      { position: 'MCD', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'DC', styles: [], ...getPos('DC') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '4-2-2-2 (Doble MO)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MC-L') },
      { position: 'MCD', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-L') },
      { position: 'MO', styles: [], ...getPos('MO-R') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
    {
    name: '4-2-3-1',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], top: 60, left: 35 },
      { position: 'MCD', styles: [], top: 60, left: 65 },
      { position: 'MDI', styles: [], top: 45, left: 15 },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'MDD', styles: [], top: 45, left: 85 },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
   {
    name: '4-2-3-1 (Extremos)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MC-L') },
      { position: 'MCD', styles: [], ...getPos('MC-R') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
  {
    name: '4-2-4',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-3-1-2 (Rombo Cerrado)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-3-2-1 (Árbol de Navidad)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-C') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-L') },
      { position: 'MO', styles: [], ...getPos('MO-R') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
  {
    name: '4-3-3 (Clásico)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'DC', styles: [], ...getPos('DC') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '4-3-3 (Ataque)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'DC', styles: [], ...getPos('DC') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '4-3-3 (Falso 9)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'SD', styles: [], ...getPos('DC') }, // False 9 as SD
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '4-3-3 (Doble Pivote)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MC-L') },
      { position: 'MCD', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'DC', styles: [], ...getPos('DC') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '4-4-1-1',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
  {
    name: '4-4-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-4-2 (Rombo)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '4-5-1',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MDI', styles: [], ...getPos('MDI') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-C') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MDD', styles: [], ...getPos('MDD') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
    {
    name: '4-5-1 (Ataque)',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'MO', styles: [], ...getPos('MO-L') },
      { position: 'MO', styles: [], ...getPos('MO-R') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
      { position: 'DC', styles: [], ...getPos('DC') },
    ],
  },
  {
    name: '5-2-1-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'MO', styles: [], ...getPos('MO-C') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: '5-2-3',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], ...getPos('LI') },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], ...getPos('LD') },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'EXI', styles: [], ...getPos('EXI') },
      { position: 'DC', styles: [], ...getPos('DC') },
      { position: 'EXD', styles: [], ...getPos('EXD') },
    ],
  },
  {
    name: '5-3-2',
    slots: [
      { position: 'PT', styles: [], ...getPos('PT') },
      { position: 'LI', styles: [], top: 70, left: 10 },
      { position: 'DFC', styles: [], ...getPos('DFC-L') },
      { position: 'DFC', styles: [], ...getPos('DFC-C') },
      { position: 'DFC', styles: [], ...getPos('DFC-R') },
      { position: 'LD', styles: [], top: 70, left: 90 },
      { position: 'MC', styles: [], ...getPos('MC-L') },
      { position: 'MCD', styles: [], ...getPos('MCD') },
      { position: 'MC', styles: [], ...getPos('MC-R') },
      { position: 'DC', styles: [], ...getPos('DC-L') },
      { position: 'DC', styles: [], ...getPos('DC-R') },
    ],
  },
  {
    name: 'Custom',
    slots: Array(11).fill(null).map((_, i) => ({
        position: 'DC',
        styles: [],
        top: 20 + Math.floor(i / 3) * 25,
        left: 25 + (i % 3) * 25,
    })),
  },
];